apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cpu-device-plugin
  namespace: default
spec:
  selector:
    matchLabels:
      name: cpu-device-plugin
  template:
    metadata:
      labels:
        name: cpu-device-plugin
    spec:
      containers:
      - name: cpu-device-plugin 
        image: cpudp
        imagePullPolicy: IfNotPresent
        command: [ "/cpu-device-plugin", "-logtostderr", "-dp-cores","7" ]
        env:
        - name: CMK_PROC_FS
          value: "/host/proc"
        volumeMounts:
        - mountPath: /var/lib/kubelet/device-plugins/ 
          name: devicesock 
          readOnly: false
        - mountPath: /opt/bin
          name: cmk-bin
          readOnly: true
        - mountPath: /etc/cmk
          name: cmk-conf
          readOnly: false
        - mountPath: /host/proc
          name: host-proc
          readOnly: false

      volumes:
      - name: devicesock 
        hostPath:
         # directory location on host
         path: /var/lib/kubelet/device-plugins/
      - name: cmk-bin
        hostPath:
         # directory location on host
         path: /opt/bin
      - name: cmk-conf
        hostPath:
         # directory location on host
         path: /etc/cmk
      - name: host-proc
        hostPath:
         # directory location on host
         path: /proc

